// Update image paths to be relative to root
const parts = [
    {
        id: 1,
        // ...existing code...
        img: "./images/submariner-black.jpg", // Update image paths
        // ...existing code...
    },
    // ...rest of parts array...
];

// ...rest of existing code...